#pragma once
#include "raylib.h"
#include "enemies.h"

/// Stores tower attack rays
struct TowerRay
{
	Vector3 origin;
	Vector3 target;
	int lifespan;
};

/// Creates rays
/// 
/// This function creates rays given the target of the ray
/// @param enemyPos the position of the target in the 3D environment
/// @return This function returns a custom struct which is later used to make rays
TowerRay createRay(Vector3 enemyPos);




/// Draws the aforementioned rays
/// 
/// This function draws the rays generated by createRay
/// @param ray the ray the function will draw
/// @return This function returns true when the ray needs to be deleted and false when it doesn't
/// @see TowerRay
bool drawRay(TowerRay& ray);